[tool.poetry]
name = "dizimo"
version = "0.1.0"
description = "Sistema de gest√£o de dizimo"
authors = ["Weverton Marques <wevertonms@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1.1"
django-jazzmin = "^2.2.7"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
prospector = "^1.3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
